apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP
  clusterIP: None # This makes it a "headless" service
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
